openapi: 3.0.0
info:
    title: Tax API
    version: 1.0.0


paths:
    /api/tax:
        post:
            tags:
                - Tax
            summary: Calculate tax
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TaxRequest'
            responses:
                '200':
                    description: Tax calculated successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TaxResponse'

    /api/match:
        get:
            tags:
                - Match
            summary: Get match details
            parameters:
                -   name: matchId
                    in: query
                    description: Unique identifier for the match
                    required: true
                    schema:
                        type: string
            responses:
                '200':
                    description: Match details retrieved successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MatchResponse'
                '404':
                    description: Match not found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'



components:
    schemas:
        Error:
            type: object
            properties:
                code:
                    type: integer
                    format: int32
                message:
                    type: string

        TaxRequest:
            type: object
            properties:
                traderId:
                    type: integer
                    format: int64
                    description: Unique identifier for the trader
                playedAmount:
                    type: number
                    description: Amount played
                odd:
                    type: number
                    description: Odds value
            required:
                - traderId
                - playedAmount
                - odd
        TaxResponse:
            type: object
            properties:
#               # Extra field???
                possibleReturnAmount:
                    type: number
                    description: Possible return amount
                possibleReturnAmountBefTax:
                    type: number
                    description: Possible return amount before tax
                possibleReturnAmountAfterTax:
                    type: number
                    description: Possible return amount after tax
                taxRate:
                    type: number
                    description: Tax rate
                taxAmount:
                    type: number
                    description: Calculated tax amount

        MatchResponse:
            type: object
            properties:
                firstEventTime:
                    type: string
                    format: instant
                    description: Instant of first processed event belonging to match
                lastEventTime:
                    type: string
                    format: instant
                    description: Instant of last processed event  belonging to match
